// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBW-iaPE31xiFPDQVXyrubjg8YYj3CeRI',
    appId: '1:362069540916:web:a5141a038f1b39666b8a61',
    messagingSenderId: '362069540916',
    projectId: 'echo-4ea97',
    authDomain: 'echo-4ea97.firebaseapp.com',
    storageBucket: 'echo-4ea97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB958C6SXQnbhnyPCyBdYp6QKngFCMyhhI',
    appId: '1:362069540916:android:0d8f87435ba31f876b8a61',
    messagingSenderId: '362069540916',
    projectId: 'echo-4ea97',
    storageBucket: 'echo-4ea97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJrpOlkQzRjMc-H4oy2_0HvjmQLiibEs',
    appId: '1:362069540916:ios:fad146425ad0b9956b8a61',
    messagingSenderId: '362069540916',
    projectId: 'echo-4ea97',
    storageBucket: 'echo-4ea97.firebasestorage.app',
    iosClientId: '362069540916-g3l1m2koo5jv7nals3qmgbk9333vie27.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneWhatsappBaseCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJrpOlkQzRjMc-H4oy2_0HvjmQLiibEs',
    appId: '1:362069540916:ios:fad146425ad0b9956b8a61',
    messagingSenderId: '362069540916',
    projectId: 'echo-4ea97',
    storageBucket: 'echo-4ea97.firebasestorage.app',
    iosClientId: '362069540916-g3l1m2koo5jv7nals3qmgbk9333vie27.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneWhatsappBaseCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBW-iaPE31xiFPDQVXyrubjg8YYj3CeRI',
    appId: '1:362069540916:web:5c576108ef6ecd9e6b8a61',
    messagingSenderId: '362069540916',
    projectId: 'echo-4ea97',
    authDomain: 'echo-4ea97.firebaseapp.com',
    storageBucket: 'echo-4ea97.firebasestorage.app',
  );

}